import { Search, UsersRound } from "lucide-react"
import { useEffect, useState } from "react"
import { Link } from "react-router-dom"

import { supabase } from "@/lib/supabase"

type Creator = { user_id: string; handle: string; display_name: string; bio: string; avatar_url: string | null }
type Reel = { id: string; title: string; caption: string; creator_id: string; creator_profiles: { handle: string } | null }

export default function CreatorDiscoveryPage() {
  const [query, setQuery] = useState("")
  const [creators, setCreators] = useState<Creator[]>([])
  const [reels, setReels] = useState<Reel[]>([])
  useEffect(() => { void Promise.all([supabase.from("creator_profiles").select("user_id,handle,display_name,bio,avatar_url").eq("discoverable", true).order("created_at", { ascending: false }).limit(30), supabase.from("reel_submissions").select("id,title,caption,creator_id,creator_profiles(handle)").eq("status", "approved").order("published_at", { ascending: false }).limit(30)]).then(([creatorResult, reelResult]) => { setCreators((creatorResult.data ?? []) as Creator[]); setReels((reelResult.data ?? []) as unknown as Reel[]) }) }, [])
  const term = query.trim().toLowerCase()
  const matches = (value: string) => !term || value.toLowerCase().includes(term)
  const creatorResults = creators.filter(creator => matches(`${creator.handle} ${creator.display_name} ${creator.bio}`))
  const reelResults = reels.filter(reel => matches(`${reel.title} ${reel.caption} ${reel.creator_profiles?.handle ?? ""}`))
  return <main className="mx-auto max-w-5xl pb-10"><section className="rounded-3xl border border-white/10 bg-[var(--dv-surface)] p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--dv-accent)]">Discover</p><h1 className="mt-2 text-3xl font-black text-white">Creators and Reels</h1><p className="mt-3 text-sm text-slate-400">Find active creators, their public profiles, and published Reels.</p><label className="relative mt-6 block"><Search className="absolute left-4 top-1/2 size-5 -translate-y-1/2 text-slate-400" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search a creator, Reel title, or #hashtag" className="w-full rounded-xl border border-white/15 bg-black/20 py-3 pl-12 pr-4 text-white" /></label></section><section className="mt-7"><div className="flex items-center gap-2"><UsersRound className="size-5 text-[var(--dv-accent)]" /><h2 className="text-xl font-black text-white">Creators</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{creatorResults.map(creator => <Link key={creator.user_id} to={`/dashboard/creator/${creator.user_id}`} className="rounded-2xl border border-white/10 bg-[var(--dv-surface)] p-4 transition hover:border-[var(--dv-accent)]/50"><div className="flex items-center gap-3">{creator.avatar_url ? <img src={creator.avatar_url} alt="" className="size-11 rounded-full object-cover" /> : <span className="grid size-11 place-items-center rounded-full bg-[var(--dv-accent)]/20 font-black text-[var(--dv-accent)]">{(creator.display_name || creator.handle).slice(0, 1).toUpperCase()}</span>}<div className="min-w-0"><strong className="block truncate text-white">{creator.display_name || creator.handle}</strong><span className="text-sm text-[var(--dv-accent)]">@{creator.handle}</span></div></div><p className="mt-3 line-clamp-2 text-sm text-slate-400">{creator.bio || "Creator on DestiVerse Vision"}</p></Link>)}</div>{!creatorResults.length ? <p className="mt-4 text-sm text-slate-400">No creator matches that search.</p> : null}</section><section className="mt-8"><h2 className="text-xl font-black text-white">Published Reels</h2><div className="mt-4 grid gap-3">{reelResults.map(reel => <Link key={reel.id} to={`/dashboard/reels/${reel.id}`} className="rounded-2xl border border-white/10 bg-[var(--dv-surface)] p-4 transition hover:border-[var(--dv-accent)]/50"><strong className="text-white">{reel.title}</strong><p className="mt-1 line-clamp-2 text-sm text-slate-400">{reel.caption || "No caption"}</p><span className="mt-2 block text-xs font-bold text-[var(--dv-accent)]">@{reel.creator_profiles?.handle || "creator"}</span></Link>)}</div>{!reelResults.length ? <p className="mt-4 text-sm text-slate-400">No Reel matches that search.</p> : null}</section></main>
}
