import { ArrowLeft, Flag, Share2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/lib/supabase';

type Reel = { id: string; title: string; caption: string; video_url: string; poster_url: string | null; creator_id: string; creator_profiles: { handle: string; display_name: string; avatar_url: string | null } | null };

export default function ReelDetailPage() {
  const { reelId } = useParams(); const { session } = useAuth(); const [reel, setReel] = useState<Reel | null>(null); const [message, setMessage] = useState('');
  useEffect(() => { if (!reelId) return; void supabase.from('reel_submissions').select('id,title,caption,video_url,poster_url,creator_id,creator_profiles(handle,display_name,avatar_url)').eq('id', reelId).eq('status', 'approved').maybeSingle().then(async ({ data }) => { if (!data) return; const { data: url } = await supabase.storage.from('creator-reels').createSignedUrl(data.video_url, 3600); setReel({ ...data, video_url: url?.signedUrl ?? data.video_url } as unknown as Reel); }); }, [reelId]);
  const report = async () => { if (!session || !reel) return; const reason = window.prompt('Why should this Reel be reviewed?'); if (!reason?.trim()) return; const { error } = await supabase.from('reel_reports').insert({ reel_id: reel.id, reporter_id: session.user.id, reason: reason.trim() }); setMessage(error ? (error.code === '23505' ? 'You have already reported this Reel.' : `Could not send your report: ${error.message}`) : 'Report sent to moderation. Thank you.'); };
  const share = async () => { if (!reel) return; if (navigator.share) await navigator.share({ title: reel.title, text: reel.caption, url: window.location.href }).catch(() => undefined); else { await navigator.clipboard?.writeText(window.location.href); setMessage('Link copied.'); } };
  if (!reel) return <main className="mx-auto max-w-3xl p-6 text-slate-400">Loading Reel…</main>;
  return <main className="mx-auto max-w-3xl pb-10"><Link to="/dashboard/reels" className="inline-flex items-center gap-2 text-sm text-white/60 hover:text-white"><ArrowLeft className="size-4" /> Back to Reels</Link><article className="mt-5 overflow-hidden rounded-3xl border border-white/10 bg-[var(--dv-surface)]"><video controls autoPlay playsInline preload="metadata" poster={reel.poster_url ?? undefined} src={reel.video_url} className="aspect-[9/13] max-h-[75dvh] w-full bg-black object-contain" /><div className="p-5 sm:p-7"><Link to={`/dashboard/creator/${reel.creator_id}`} className="inline-flex items-center gap-2 rounded-full pr-3 text-sm font-bold text-[var(--dv-accent)] hover:bg-white/10"><span className="grid size-9 place-items-center overflow-hidden rounded-full border border-white/20 bg-[var(--dv-accent)]/20">{reel.creator_profiles?.avatar_url ? <img src={reel.creator_profiles.avatar_url} alt="" className="size-full object-cover" /> : (reel.creator_profiles?.handle || 'C').slice(0, 1).toUpperCase()}</span>@{reel.creator_profiles?.handle || 'creator'}</Link><h1 className="mt-3 text-3xl font-black text-white">{reel.title}</h1>{reel.caption ? <p className="mt-3 leading-7 text-slate-300">{reel.caption}</p> : null}<div className="mt-6 flex flex-wrap gap-3"><button type="button" onClick={() => void share()} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-bold text-black"><Share2 className="size-4" /> Share</button>{session && session.user.id !== reel.creator_id ? <button type="button" onClick={() => void report()} className="inline-flex items-center gap-2 rounded-xl border border-white/15 px-4 py-3 text-sm font-bold text-white"><Flag className="size-4" /> Report Reel</button> : null}</div>{message ? <p className="mt-4 text-sm text-slate-300">{message}</p> : null}</div></article></main>;
}
