import { Bookmark, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '@/contexts/AuthContext'
import { supabase } from '@/lib/supabase'

type Reel = { id: string; title: string; caption: string; video_url: string; poster_url: string | null }

export default function SavedReelsPage() {
  const { session } = useAuth(); const [reels, setReels] = useState<Reel[]>([]); const [message, setMessage] = useState('')
  useEffect(() => { if (!session) return; void (async () => { const { data: saves, error } = await supabase.from('reel_saves').select('reel_id,created_at').eq('user_id', session.user.id).order('created_at', { ascending: false }); if (error) { setMessage(error.message); return } const ids = (saves ?? []).map(row => row.reel_id); if (!ids.length) return; const { data } = await supabase.from('reel_submissions').select('id,title,caption,video_url,poster_url').in('id', ids); const indexed = new Map((data ?? []).map(row => [row.id, row as Reel])); setReels(ids.map(id => indexed.get(id)).filter((row): row is Reel => Boolean(row))) })() }, [session])
  const remove = async (id: string) => { if (!session) return; const { error } = await supabase.from('reel_saves').delete().eq('user_id', session.user.id).eq('reel_id', id); if (error) setMessage(error.message); else setReels(all => all.filter(reel => reel.id !== id)) }
  return <main className="mx-auto max-w-5xl pb-10"><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--dv-accent)]">Your library</p><h1 className="mt-2 text-3xl font-black text-white">Saved Reels</h1><p className="mt-3 text-sm text-slate-400">Reels you save are private to your account and appear here on any signed-in device.</p>{reels.length ? <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{reels.map(reel => <article key={reel.id} className="overflow-hidden rounded-2xl border border-white/10 bg-[var(--dv-surface)]"><Link to={`/dashboard/reels?reel=${reel.id}`}><div className="aspect-[9/14] bg-black">{reel.poster_url ? <img src={reel.poster_url} alt="" className="size-full object-cover" /> : <video src={reel.video_url} muted preload="metadata" className="size-full object-cover" />}</div><div className="p-3"><b className="line-clamp-1 text-sm text-white">{reel.title}</b><p className="mt-1 line-clamp-2 text-xs text-slate-400">{reel.caption}</p></div></Link><button type="button" onClick={() => void remove(reel.id)} className="m-3 inline-flex items-center gap-2 text-xs font-bold text-slate-300"><Trash2 className="size-3.5" />Remove</button></article>)}</div> : <div className="mt-6 rounded-3xl border border-dashed border-white/15 p-10 text-center text-slate-400"><Bookmark className="mx-auto size-7" /><p className="mt-3">Save a Reel and it will appear here.</p><Link to="/dashboard/reels" className="mt-4 inline-block font-bold text-[var(--dv-accent)]">Browse Reels</Link></div>}{message ? <p className="mt-4 text-sm text-slate-300">{message}</p> : null}</main>
}
