import { Bell, CircleUserRound, DatabaseZap, ExternalLink, Info, LogOut, Mail, RefreshCw, ShieldCheck, Trash2, Volume2 } from "lucide-react"
import { useEffect, useState } from "react"
import { Link, useNavigate } from "react-router-dom"
import { useAuth } from "@/contexts/AuthContext"
import { supabase } from "@/lib/supabase"
import { clearOfflineDownloads, getOfflineRecords } from "@/services/offline"
import { signOut } from "@/services/auth"

type Preferences = { autoplay: boolean; reduced_data: boolean; email_updates: boolean; notifications_enabled: boolean; creator_updates: boolean; payment_updates: boolean; captions_enabled: boolean; playback_speed: number; video_quality: "auto" | "data_saver" | "high"; reduce_motion: boolean; profile_visibility: "public" | "private" }
type PreferenceRow = [keyof Preferences, string, string]

function ToggleRows({
  items,
  prefs,
  onToggle,
}: {
  items: PreferenceRow[]
  prefs: Preferences
  onToggle: (key: keyof Preferences, value: boolean) => void
}) {
  return (
    <div className="mt-5 space-y-3">
      {items.map(([key, label, detail]) => (
        <label key={key} className="flex cursor-pointer items-start justify-between gap-5 rounded-xl border border-[var(--dv-border)] bg-black/10 p-4">
          <span>
            <strong className="block text-sm text-white">{label}</strong>
            <span className="mt-1 block text-xs font-normal text-slate-400">{detail}</span>
          </span>
          <input
            type="checkbox"
            checked={Boolean(prefs[key])}
            onChange={(event) => onToggle(key, event.target.checked)}
            className="mt-1 size-4 accent-[var(--dv-accent)]"
          />
        </label>
      ))}
    </div>
  )
}

const defaults: Preferences = {
  autoplay: true,
  reduced_data: false,
  email_updates: true,
  notifications_enabled: true,
  creator_updates: true,
  payment_updates: true,
  captions_enabled: true,
  playback_speed: 1,
  video_quality: "auto",
  reduce_motion: false,
  profile_visibility: "public",
}

export default function SettingsPage() {
  const { session } = useAuth(); const navigate = useNavigate()
  const [prefs, setPrefs] = useState(defaults); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false)
  const [isAdmin, setIsAdmin] = useState(false); const [isCreator, setIsCreator] = useState(false); const [discoverable, setDiscoverable] = useState(true)
  const [blocked, setBlocked] = useState<string[]>([]); const [offlineCount, setOfflineCount] = useState(0); const [adFreeUntil, setAdFreeUntil] = useState<string | null>(null)
  const [email, setEmail] = useState(session?.user.email ?? ""); const [deletionReason, setDeletionReason] = useState("")
  useEffect(() => { if (!session?.user.id) return; let live = true; void (async () => { const [preferences, admin, creator, blocks, pass] = await Promise.all([supabase.from("user_preferences").select("*").eq("user_id", session.user.id).maybeSingle(), supabase.rpc("is_admin"), supabase.from("creator_profiles").select("discoverable").eq("user_id", session.user.id).maybeSingle(), supabase.from("creator_blocks").select("creator_id").eq("blocker_id", session.user.id), supabase.from("user_ad_free_passes").select("expires_at").eq("user_id", session.user.id).maybeSingle()]); if (!live) return; setPrefs({ ...defaults, ...(preferences.data ?? {}) }); setIsAdmin(admin.data === true); setIsCreator(Boolean(creator.data)); setDiscoverable(creator.data?.discoverable ?? true); setBlocked((blocks.data ?? []).map((item) => item.creator_id)); setAdFreeUntil(pass.data?.expires_at ?? null); setOfflineCount(getOfflineRecords().length) })(); return () => { live = false } }, [session?.user.id])
  const save = async (next: Preferences) => { if (!session?.user.id) return; setPrefs(next); const { error } = await supabase.from("user_preferences").upsert({ user_id: session.user.id, ...next, updated_at: new Date().toISOString() }); if (error) setNotice(error.message) }
  const toggle = (key: keyof Preferences, value: boolean) => void save({ ...prefs, [key]: value } as Preferences)
  const changeEmail = async () => { setBusy(true); const { error } = await supabase.auth.updateUser({ email: email.trim() }); setNotice(error ? error.message : "Check your current and new email addresses to confirm this change."); setBusy(false) }
  const clearOffline = async () => { setBusy(true); await clearOfflineDownloads(); setOfflineCount(0); setNotice("Offline downloads were removed from this device."); setBusy(false) }
  const updateCreator = async (value: boolean) => { if (!session?.user.id) return; setDiscoverable(value); const { error } = await supabase.from("creator_profiles").update({ discoverable: value }).eq("user_id", session.user.id); if (error) { setDiscoverable(!value); setNotice(error.message) } }
  const unblock = async (creatorId: string) => { if (!session?.user.id) return; const { error } = await supabase.from("creator_blocks").delete().eq("blocker_id", session.user.id).eq("creator_id", creatorId); if (error) setNotice(error.message); else setBlocked((all) => all.filter((id) => id !== creatorId)) }
  const requestDeletion = async () => { if (!session?.user.id || !window.confirm("Request account deletion? An administrator will review it before your account is removed.")) return; setBusy(true); const { error } = await supabase.from("account_deletion_requests").upsert({ user_id: session.user.id, reason: deletionReason.trim(), status: "open" }, { onConflict: "user_id" }); setNotice(error ? error.message : "Deletion request received. You can continue using the app while it is reviewed."); setBusy(false) }
  const rows: Array<[keyof Preferences, string, string]> = [["autoplay", "Autoplay next video", "Start the next available video automatically."], ["reduced_data", "Reduce data use", "Prefer lower-data loading where supported."], ["captions_enabled", "Captions by default", "Enable captions when provided."], ["reduce_motion", "Reduce motion", "Limit decorative animation."], ["email_updates", "Product email updates", "Allow future product-update emails."], ["notifications_enabled", "In-app notifications", "Show DestiVerse notifications."], ["creator_updates", "Creator updates", "Receive creator, Reel, and follow updates."], ["payment_updates", "Payment and Coin updates", "Receive payment, Coin, and pass updates."]]
  const adminUrl = import.meta.env.VITE_ADMIN_APP_URL || "http://localhost:5174"; const googleConnected = session?.user.identities?.some((identity) => identity.provider === "google") ?? false
  return <main className="mx-auto max-w-3xl space-y-6 pb-8"><section className="dv-surface rounded-[var(--dv-radius-card)] border border-[var(--dv-border)] p-6 shadow-[var(--dv-shadow-card)] sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--dv-accent)]">Your experience</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-white">Settings</h1><p className="mt-3 text-sm text-slate-400">Account, privacy, notifications, playback, and device controls.</p></section>
    <section className="dv-surface rounded-[var(--dv-radius-card)] border border-[var(--dv-border)] p-6 shadow-[var(--dv-shadow-card)]"><div className="flex items-center gap-3"><Volume2 className="size-5 text-[var(--dv-accent)]" /><div><h2 className="text-xl font-semibold text-white">Playback and accessibility</h2><p className="text-sm text-slate-400">Saved to your DestiVerse account.</p></div></div><ToggleRows items={rows.slice(0, 4)} prefs={prefs} onToggle={toggle} /><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold text-white">Video quality<select value={prefs.video_quality} onChange={(event) => void save({ ...prefs, video_quality: event.target.value as Preferences["video_quality"] })} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-white"><option value="auto">Auto</option><option value="data_saver">Data Saver</option><option value="high">High Quality</option></select></label><label className="text-sm font-semibold text-white">Playback speed<select value={prefs.playback_speed} onChange={(event) => void save({ ...prefs, playback_speed: Number(event.target.value) })} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-white">{[0.75, 1, 1.25, 1.5, 2].map((speed) => <option key={speed} value={speed}>{speed}×</option>)}</select></label></div></section>
    <section className="dv-surface rounded-[var(--dv-radius-card)] border border-[var(--dv-border)] p-6 shadow-[var(--dv-shadow-card)]"><div className="flex items-center gap-3"><Bell className="size-5 text-[var(--dv-accent)]" /><div><h2 className="text-xl font-semibold text-white">Notifications</h2><p className="text-sm text-slate-400">Choose which DestiVerse updates you receive.</p></div></div><ToggleRows items={rows.slice(4)} prefs={prefs} onToggle={toggle} /></section>
    <section className="dv-surface rounded-[var(--dv-radius-card)] border border-[var(--dv-border)] p-6 shadow-[var(--dv-shadow-card)]"><div className="flex items-center gap-3"><DatabaseZap className="size-5 text-[var(--dv-accent)]" /><div><h2 className="text-xl font-semibold text-white">Offline and membership</h2><p className="text-sm text-slate-400">Offline files remain only in this browser.</p></div></div><div className="mt-5 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-[var(--dv-border)] bg-black/10 p-4"><span className="text-sm text-white"><strong>{offlineCount}</strong> offline download{offlineCount === 1 ? "" : "s"}</span><button type="button" disabled={busy || !offlineCount} onClick={() => void clearOffline()} className="rounded-xl border border-white/15 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Clear offline files</button></div><Link to="/dashboard/membership" className="mt-4 flex items-center justify-between rounded-xl border border-[var(--dv-accent)]/30 bg-[var(--dv-accent)]/10 p-4 text-sm text-white"><span><strong className="block">Membership, Coins, and ads</strong><span className="text-xs text-slate-300">{adFreeUntil && new Date(adFreeUntil) > new Date() ? `Ad-free until ${new Date(adFreeUntil).toLocaleString()}` : "Premium is ad-free; free viewers can use Coins for a one-day ad-free pass."}</span></span><ExternalLink className="size-4" /></Link></section>
    <section className="dv-surface rounded-[var(--dv-radius-card)] border border-[var(--dv-border)] p-6 shadow-[var(--dv-shadow-card)]"><div className="flex items-center gap-3"><CircleUserRound className="size-5 text-[var(--dv-accent)]" /><div><h2 className="text-xl font-semibold text-white">Profile and privacy</h2><p className="text-sm text-slate-400">Control profile discovery and blocked creators.</p></div></div><label className="mt-5 flex items-center justify-between gap-4 rounded-xl border border-[var(--dv-border)] bg-black/10 p-4"><span><strong className="block text-sm text-white">Profile visibility</strong><span className="text-xs text-slate-400">Private hides your profile from new public discovery.</span></span><select value={prefs.profile_visibility} onChange={(event) => void save({ ...prefs, profile_visibility: event.target.value as Preferences["profile_visibility"] })} className="rounded-lg bg-black/30 p-2 text-sm text-white"><option value="public">Public</option><option value="private">Private</option></select></label>{isCreator ? <label className="mt-3 flex items-center justify-between gap-4 rounded-xl border border-[var(--dv-border)] bg-black/10 p-4"><span><strong className="block text-sm text-white">Creator discovery</strong><span className="text-xs text-slate-400">Show approved Reels and your creator profile in discovery.</span></span><input type="checkbox" checked={discoverable} onChange={(event) => void updateCreator(event.target.checked)} className="size-4 accent-[var(--dv-accent)]" /></label> : null}<div className="mt-4 rounded-xl border border-[var(--dv-border)] bg-black/10 p-4"><strong className="text-sm text-white">Blocked creators</strong>{blocked.length ? blocked.map((id) => <div className="mt-3 flex items-center justify-between gap-3" key={id}><span className="truncate text-xs text-slate-300">{id}</span><button type="button" onClick={() => void unblock(id)} className="rounded-lg border border-white/15 px-2 py-1 text-xs font-semibold text-white">Unblock</button></div>) : <p className="mt-2 text-xs text-slate-400">No blocked creators.</p>}</div></section>
    <section className="dv-surface rounded-[var(--dv-radius-card)] border border-[var(--dv-border)] p-6 shadow-[var(--dv-shadow-card)]"><div className="flex items-center gap-3"><ShieldCheck className="size-5 text-[var(--dv-accent)]" /><div><h2 className="text-xl font-semibold text-white">Account and security</h2><p className="text-sm text-slate-400">Signed in as {session?.user.email}.</p></div></div><label className="mt-5 block text-sm font-semibold text-white">Email address<div className="mt-2 flex gap-2"><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-white" /><button type="button" disabled={busy} onClick={() => void changeEmail()} className="rounded-xl border border-white/15 px-3 text-sm font-semibold text-white">Update</button></div></label><div className="mt-4 rounded-xl border border-[var(--dv-border)] bg-black/10 p-4"><strong className="flex items-center gap-2 text-sm text-white"><Mail className="size-4" /> Google sign-in</strong><p className="mt-1 text-xs text-slate-400">{googleConnected ? "Google is connected to your account." : "Google is not connected. You can connect it by using Google sign-in."}</p></div><div className="mt-4 flex flex-wrap gap-3"><Link to="/reset-password" className="rounded-xl border border-[var(--dv-border)] px-4 py-3 text-sm font-semibold text-white">Reset password</Link><button type="button" disabled={busy} onClick={() => void supabase.auth.signOut({ scope: "others" }).then(({ error }) => setNotice(error?.message || "Other devices signed out."))} className="rounded-xl border border-[var(--dv-border)] px-4 py-3 text-sm font-semibold text-white">Sign out other devices</button><Link to="/help" className="rounded-xl border border-[var(--dv-border)] px-4 py-3 text-sm font-semibold text-white">Help center</Link><button type="button" onClick={() => window.location.reload()} className="inline-flex items-center gap-2 rounded-xl border border-[var(--dv-border)] px-4 py-3 text-sm font-semibold text-white"><RefreshCw className="size-4" /> Refresh</button><button type="button" onClick={() => void signOut().then(() => navigate("/", { replace: true }))} className="inline-flex items-center gap-2 rounded-xl border border-red-400/30 px-4 py-3 text-sm font-semibold text-red-200"><LogOut className="size-4" /> Sign out</button></div></section>
    <section className="rounded-[var(--dv-radius-card)] border border-red-400/25 bg-red-500/[.06] p-6"><div className="flex items-center gap-3"><Trash2 className="size-5 text-red-300" /><div><h2 className="text-xl font-semibold text-white">Delete account</h2><p className="text-sm text-slate-300">Requests are reviewed before an account is removed.</p></div></div><textarea value={deletionReason} maxLength={500} onChange={(event) => setDeletionReason(event.target.value)} placeholder="Optional reason" className="mt-4 min-h-20 w-full rounded-xl border border-red-300/20 bg-black/20 p-3 text-sm text-white" /><button type="button" disabled={busy} onClick={() => void requestDeletion()} className="mt-3 rounded-xl border border-red-300/30 px-4 py-3 text-sm font-semibold text-red-200">Request account deletion</button></section>
    {isAdmin ? <section className="rounded-[var(--dv-radius-card)] border border-[var(--dv-accent)]/30 bg-[var(--dv-accent)]/10 p-6"><div className="flex items-center gap-3"><Info className="size-5 text-[var(--dv-accent)]" /><div><h2 className="text-xl font-semibold text-white">Admin access</h2><p className="text-sm text-slate-300">Your account has administrator access.</p></div></div><a href={adminUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[var(--dv-accent)] px-4 py-3 text-sm font-semibold text-white">Open control panel <ExternalLink className="size-4" /></a></section> : null}{notice ? <p role="status" className="rounded-xl border border-white/10 bg-white/[.04] p-3 text-sm text-slate-200">{notice}</p> : null}</main>
}
